// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB151DiIdSE5XqyflTyCOLLHP2fT1KjTRA',
    appId: '1:195642335957:web:0f877b068b18486c16f85c',
    messagingSenderId: '195642335957',
    projectId: 'fruit-hub-48433',
    authDomain: 'fruit-hub-48433.firebaseapp.com',
    storageBucket: 'fruit-hub-48433.firebasestorage.app',
    measurementId: 'G-GGXT1QBWEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCflO5fhJVlLqvUzvxhjGj2Y1Gz23hLcFQ',
    appId: '1:195642335957:android:be1c42b14f10af1a16f85c',
    messagingSenderId: '195642335957',
    projectId: 'fruit-hub-48433',
    storageBucket: 'fruit-hub-48433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeMPI9caxBUBY3dNOQaNb3i1LCnT_69xk',
    appId: '1:195642335957:ios:f38b47ab7a3bd05d16f85c',
    messagingSenderId: '195642335957',
    projectId: 'fruit-hub-48433',
    storageBucket: 'fruit-hub-48433.firebasestorage.app',
    iosBundleId: 'com.example.fruitHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeMPI9caxBUBY3dNOQaNb3i1LCnT_69xk',
    appId: '1:195642335957:ios:f38b47ab7a3bd05d16f85c',
    messagingSenderId: '195642335957',
    projectId: 'fruit-hub-48433',
    storageBucket: 'fruit-hub-48433.firebasestorage.app',
    iosBundleId: 'com.example.fruitHubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB151DiIdSE5XqyflTyCOLLHP2fT1KjTRA',
    appId: '1:195642335957:web:264ddd2cb294224316f85c',
    messagingSenderId: '195642335957',
    projectId: 'fruit-hub-48433',
    authDomain: 'fruit-hub-48433.firebaseapp.com',
    storageBucket: 'fruit-hub-48433.firebasestorage.app',
    measurementId: 'G-2QGN8T923K',
  );
}
